name: Azure Network Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5  # or your desired version

      # 3️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 

      # 4️⃣ Terraform Init
      - name: Terraform Init
        run: terraform -chdir=env/production init

      # 5️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=env/production plan -out=tfplan -var "admin_username=azureuser" -var "location=UK South"

      # 6️⃣ Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=env/production apply -auto-approve tfplan
