name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.1

      # 3. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 4. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 5. Import existing Resource Group (ignore errors if already imported)
      - name: Terraform Import Resource Group
        run: |
          terraform import azurerm_resource_group.rg_securenetwork /subscriptions/ec248675-1d06-41c0-a954-557ab9cf7127/resourceGroups/Secure-Network || true

      # 6. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 7. Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve
